export const EstilosTatuagem = [
  'Aquarela',
  'Black Work',
  'Biomecânica',
  'Celta',
  'Comics',
  'Colorida',
  'Freehand',
  'Geométrico',
  'Gray Wash',
  'Lettering',
  'Mandala',
  'Maori',
  'New School',
  'Old School',
  'Oriental',
  'Pontilhismo',
  'Portrait',
  'Realismo',
  'Traços Finos',
  'Tribal',
];
